# Generated by Django 3.1 on 2020-08-24 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Drafts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('to', models.CharField(max_length=100)),
                ('subject', models.CharField(max_length=200)),
                ('content', models.CharField(max_length=256)),
                ('create_date', models.DateTimeField(verbose_name='创建日期')),
                ('attachment', models.FilePathField(default='')),
                ('is_del', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Inbox',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender', models.CharField(max_length=100)),
                ('receive_date', models.DateTimeField(verbose_name='创建日期')),
                ('subject', models.CharField(max_length=200)),
                ('content', models.CharField(max_length=256)),
                ('attachment', models.FilePathField(default='')),
                ('is_del', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Outbox',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('to', models.CharField(max_length=100)),
                ('subject', models.CharField(max_length=200)),
                ('content', models.CharField(max_length=256)),
                ('create_date', models.DateTimeField(verbose_name='创建日期')),
                ('attachment', models.FilePathField(default='')),
                ('is_del', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.EmailField(max_length=254)),
                ('create_date', models.DateTimeField(verbose_name='创建日期')),
                ('is_del', models.IntegerField(default=0)),
                ('frozen', models.IntegerField(default=0)),
                ('password', models.CharField(max_length=60)),
            ],
        ),
    ]
