# Generated by Django 3.1 on 2020-08-28 05:45

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('e_mail', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drafts',
            name='create_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 8, 28, 5, 45, 28, 854527, tzinfo=utc), verbose_name='创建日期'),
        ),
        migrations.AlterField(
            model_name='inbox',
            name='receive_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 8, 28, 5, 45, 28, 854527, tzinfo=utc), verbose_name='创建日期'),
        ),
        migrations.AlterField(
            model_name='outbox',
            name='create_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 8, 28, 5, 45, 28, 854527, tzinfo=utc), verbose_name='创建日期'),
        ),
        migrations.AlterField(
            model_name='user',
            name='create_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 8, 28, 5, 45, 28, 811648, tzinfo=utc), verbose_name='创建日期'),
        ),
    ]
